# This is a sample build configuration for Javascript.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:4.6.0
clone:           # the 'clone' section 
  depth: 5       # the depth, in this case the clone will contain last five commits
 
pipelines:
  default:
    - step:
        script:
          - echo "Clone all the things!"